services:
  nginx:
    ports:
      - '80:80'
    # В dev режиме не используем SSL
    command: 'nginx -g "daemon off;"'

  server:
    build:
      target: dev
    volumes:
      - ./server/static:/app/static
      - ./server:/app  # Монтируем исходный код для hot reload
      - /app/node_modules
    ports:
      - 5000:5000
    command: yarn run start:dev  # Dev команда
    environment:
      - NODE_ENV=dev
    # Убираем лимиты для разработки

  postgres:
    environment:
      POSTGRES_DB: prod_db
    ports:
      - '5020:5432'
    # В dev можно убрать лимиты или сделать их меньше