FROM node:alpine As dev

WORKDIR /app

COPY package*.json yarn.lock ./
COPY server/package.json ./server/
RUN yarn install --frozen-lockfile

COPY server ./server
WORKDIR /app/server
RUN yarn build

FROM node:alpine as prod

WORKDIR /app/server

COPY --from=dev /app/server/dist ./server/dist
COPY --from=dev /app/server/node_modules ./server/node_modules
COPY --from=dev /app/server/package.json ./server

EXPOSE 5000

CMD ["node", "dist/main"]