FROM node:alpine as frontend

WORKDIR /app

COPY package*.json yarn.lock ./
COPY client/package.json ./client/
RUN yarn install --frozen-lockfile

COPY client ./client
WORKDIR /app/client
RUN yarn build

# Создаем финальный образ
FROM nginx:stable-alpine
COPY --from=frontend /app/client/dist /usr/share/nginx/html

ARG MODE=dev
ENV MODE=${MODE}

COPY nginx.${MODE}.conf /etc/nginx/nginx.conf

EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]
