/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/report-violation': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Сообщение о нарушении правил */
		post: operations['AdminController_reportViolation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-foul-messages': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список сообщений, нарушающих правила */
		get: operations['AdminController_getFoulMessages'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/fetch-cleaning-is-complete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Сообщение о нарушении правил */
		post: operations['AdminController_fetchCleaningIsComplete'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/upload-files': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавление нового файла */
		post: operations['FilesController_uploadFile'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/file/{filename}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['FilesController_getFile'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/send-message': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавление нового сообщения */
		post: operations['MessagesController_addMessage'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-all-messages': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение всех сообщений для определенного location */
		get: operations['MessagesController_getAllMessage'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-count-no-read-messages': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение количества всех сообщений для определенного location */
		get: operations['MessagesController_getCountNoReadMessages'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-end-read-messages-id': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение id последнего прочитанного сообщения для определенного location */
		get: operations['MessagesController_getEndReadMessagesId'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/set-end-read-messages-id': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Устанавливает последнее прочитанное сообщение для определенного location */
		post: operations['MessagesController_setEndReadMessagesId'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-message-from-id': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение сообщения по его Id */
		get: operations['MessagesController_getMessageFromId'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/blocked-message': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Блокировка сообщений */
		post: operations['MessagesController_blockedMessages'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/all-residencys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить всех пользователей */
		get: operations['ResidencyController_getAllResydencys'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-all-roles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список ролей */
		get: operations['RolesController_getAllRoles'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/create-new-role': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Создать новую роль */
		post: operations['RolesController_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/refresh-tokens': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Обновить токены для пользователя (требуется refreshToken в заголовке) */
		post: operations['TokensController_refreshTokens'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить всех пользователей */
		get: operations['UsersController_getAllUsers'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/add-role': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавить роль пользователю */
		post: operations['UsersController_userAddRole'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/remove-role': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Удалить роль у пользователя */
		delete: operations['UsersController_userRemoveRole'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/create-residency': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Сохранить место жительства */
		post: operations['UsersController_createResidency'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/add-declaration': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Авторизация пользователя */
		post: operations['UsersController_addDeclaration'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-declaration/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Авторизация пользователя */
		get: operations['UsersController_getDeclaration'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/updata-personale/{secret}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Изменение персональных данных */
		post: operations['UsersController_udatePersonaleData'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/upload-avatar': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Изменение аватара */
		post: operations['UsersController_uploadAvatar'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/blocked-user': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Блокировка пользователя, нарушившего правила */
		post: operations['UsersController_blockedUser'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/check-blocked': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Проверить блокировку пользователя и время блокировки */
		get: operations['UsersController_checkBlocked'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-user/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить пользователя */
		get: operations['UsersController_getUser'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/add-location': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавить место жительства */
		post: operations['LocationController_crateLocation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/country': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список стран */
		get: operations['LocationController_getAllCountry'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/region/{country}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список регионов */
		get: operations['LocationController_getRegions'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/locality/{region}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получить список районов */
		get: operations['LocationController_getLocality'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/send-publication': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавление нового сообщения */
		post: operations['PublicationsController_addPublication'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-all-publications': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение всех сообщений для определенного location */
		get: operations['PublicationsController_getAllPublication'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-publication/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение публикации по id */
		get: operations['PublicationsController_getDeclaration'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-user-publications': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение всех сообщений для определенного пользователя */
		get: operations['PublicationsController_getUserPublication'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/blocked-publication': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Блокировка сообщений */
		post: operations['PublicationsController_blockedPublications'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/create-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Создание новой группы */
		post: operations['GroupsController_createGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-all-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение всех групп для определенного location */
		get: operations['GroupsController_getAllPublication'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-group/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение группы по id */
		get: operations['GroupsController_getGroupFromId'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-all-posts-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение всех сообщений для определенной группы */
		get: operations['GroupsController_getAllChatPosts'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/send-post-to-chat': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Добавление нового сообщения */
		post: operations['GroupsController_addMessage'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/join-the-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Вступить в группу */
		post: operations['GroupsController_joinTheGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/leave-the-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Выйти из группы */
		post: operations['GroupsController_leaveTheGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/get-post-group-from-id': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Получение сообщения по его Id */
		get: operations['GroupsController_getPostGroupFromId'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/blocked-post-group': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Блокировка сообщений */
		post: operations['GroupsController_blockedPostGroup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Разлогинить пользователя (Удалить refreshToken у пользователя) */
		post: operations['AuthController_logout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/set-registration': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Авторизация пользователя */
		post: operations['AuthController_setRegistration'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/delete-profile': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Удалить пользователя */
		post: operations['AuthController_deleteProfile'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/restore-profile': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Восстановить профиль пользователя */
		post: operations['AuthController_restoreProfile'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/loginByVk': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Auth через VK SDK */
		post: operations['AuthController_registrationVk'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/check-admin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Проверка на наличие прав администратора. (Необходим JWT токен) */
		get: operations['AuthController_checkAdmin'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/webhook': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['TelegramController_handleUpdate'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		FoulSendMessageDto: {
			/**
			 * @description id уборщика
			 * @example 1
			 */
			id_cleaner: number;
			/**
			 * @description id сообщения нарушающего правила
			 * @example 1
			 */
			id_foul_message: number;
			/**
			 * @description Список индексов нарушенных правил
			 * @example [
			 *       1,
			 *       2,
			 *       3
			 *     ]
			 */
			selectedRules: string[];
			/**
			 * @description Действие с сообщением, нарушающим правила
			 * @example 1
			 */
			selectedActionWithFoul: number;
			/**
			 * @description Выбранное наказание для нарушителя правил
			 * @example 1
			 */
			selectedPunishment: number;
			/**
			 * @description Источник нарушения правил - название таблицы
			 * @example messages
			 */
			source: string;
		};
		FileDto: {
			id: number;
			fileName: string;
			fileNameUuid: string;
		};
		FormDto: {
			message: string;
			files: components['schemas']['FileDto'][];
			video?: string[];
		};
		CreateMessageDto: {
			/**
			 * @description Радиус проживания
			 * @example locality
			 */
			location: string;
			form: components['schemas']['FormDto'];
		};
		CreateLocationDto: {
			/**
			 * @description Название планеты
			 * @example Мир
			 */
			world: string;
			/**
			 * @description Название страны
			 * @example Россия
			 */
			country: string;
			/**
			 * @description Название региона
			 * @example Чувашия
			 */
			region: string;
			/**
			 * @description Название района
			 * @example Алатырский
			 */
			locality: string;
		};
		EndMessageDto: {
			/**
			 * @description id пользователя
			 * @example 1
			 */
			id: string;
			/**
			 * @description Проверка состояния
			 * @example sdfsfsdgggg
			 */
			secret: string;
			residency: components['schemas']['CreateLocationDto'];
		};
		EndReadMessageDto: {
			/**
			 * @description id сообщения
			 * @example 1
			 */
			id_message: number;
			/**
			 * @description Страна, регион, или район
			 * @example Место жительства
			 */
			location: string;
		};
		BlockedMessagesDto: {
			/**
			 * @description id сообщения
			 * @example 1
			 */
			id_message: number;
			/**
			 * @description Индекс действия по отношению к сообщениям
			 * @example 1
			 */
			selectedActionIndex: number;
		};
		Residency: Record<string, never>;
		CreateRoleDto: {
			/**
			 * @description Название существующей роли
			 * @example admin
			 */
			value: string;
		};
		UuidDevice: {
			/**
			 * @description uuid device
			 * @example sdfsdfsd
			 */
			uuid: string;
		};
		Role: Record<string, never>;
		Token: Record<string, never>;
		Declaration: Record<string, never>;
		Publications: {
			id: number;
			message: string;
			video: string[];
			country: string;
			region: string;
			locality: string;
			blocked: boolean;
			userId: number;
			user: components['schemas']['User'];
			files: components['schemas']['Files'][];
		};
		ChatGroup: {
			id: number;
			groupId: number;
			message: string;
			video: string[];
			location: string;
			blocked: boolean;
			userId: number;
			user: components['schemas']['User'];
			files: components['schemas']['Files'][];
		};
		Files: {
			id: number;
			fileName: string;
			fileNameUuid: string;
			messageId: number;
			messages: components['schemas']['Messages'];
			publicationId: number;
			publications: components['schemas']['Publications'];
			chatId: number;
			chat: components['schemas']['ChatGroup'];
		};
		Messages: {
			id: number;
			message: string;
			video: string[];
			location: string;
			blocked: boolean;
			userId: number;
			user: components['schemas']['User'];
			files: components['schemas']['Files'][];
		};
		ManageMessages: Record<string, never>;
		EndReadMessage: Record<string, never>;
		LastReadPostChat: Record<string, never>;
		Group: {
			id: number;
			name: string;
			task: string;
			avatar: string;
			world: string;
			country: string;
			region: string;
			locality: string;
			blocked: boolean;
			userId: number;
			users: components['schemas']['User'][];
			admins: components['schemas']['User'][];
		};
		User: {
			id: number;
			vk_id: number;
			first_name: string;
			last_name: string;
			photo_50: string;
			photo_max: string;
			isDelProfile: boolean;
			isRegistration: boolean;
			/**
			 * Format: date-time
			 * @description Дата создания записи
			 */
			dateEditResidency?: string;
			blocked: boolean;
			blockedforever: boolean;
			/**
			 * Format: date-time
			 * @description Дата создания записи
			 */
			blockeduntil?: string;
			secret: string;
			tg_id: number;
			roles: components['schemas']['Role'][];
			residencyId: number;
			residency: components['schemas']['Residency'];
			tokens: components['schemas']['Token'][];
			declaration: components['schemas']['Declaration'];
			messages: components['schemas']['Messages'][];
			manageMessages: components['schemas']['ManageMessages'][];
			endReadMessage: components['schemas']['EndReadMessage'][];
			lastReadPostChat: components['schemas']['LastReadPostChat'][];
			publications: components['schemas']['Publications'][];
			messagesChat: components['schemas']['ChatGroup'][];
			userGroups: components['schemas']['Group'][];
			adminGroups: components['schemas']['Group'][];
		};
		OutputUserAndTokens: {
			/**
			 * @description Пользователь сайта
			 * @example 1
			 */
			user: components['schemas']['User'];
			/**
			 * @description uuid
			 * @example sdfsdf
			 */
			secret: string;
			/**
			 * @description JWT токен
			 * @example aksjwelWe4kjldfksjas
			 */
			token: string;
			/**
			 * @description JWT refresh токен
			 * @example aksjwelWe4kjldfksjas
			 */
			refreshToken: string;
		};
		AddRoleDto: {
			/**
			 * @description Название существующей роли
			 * @example admin
			 */
			value: string;
			/**
			 * @description Идентификатор пользователя
			 * @example 1
			 */
			userId: number;
		};
		CreateResidencyDto: {
			/**
			 * @description id пользователя
			 * @example 1
			 */
			id: number;
			/**
			 * @description Название страны
			 * @example Россия
			 */
			country: string;
			/**
			 * @description Название региона
			 * @example Чувашия
			 */
			region: string;
			/**
			 * @description Название района
			 * @example Алатырский
			 */
			locality: string;
			/**
			 * @description Проверка состояния
			 * @example sdfsfsdgggg
			 */
			secret: string;
		};
		CreateDeclarationDto: {
			/**
			 * @description id пользователя
			 * @example 1
			 */
			id: number;
			/**
			 * @description Декларация Родной партии
			 * @example Декларация
			 */
			declaration: string;
			/**
			 * @description Проверка состояния
			 * @example sdfsfsdgggg
			 */
			secret: string;
		};
		UpdatePersonaleDto: {
			/**
			 * @description id пользователя
			 * @example 1
			 */
			user_id: number;
			/**
			 * @description Новое имя пользователя
			 * @example Имя
			 */
			first_name: string;
			/**
			 * @description Новая фамилия пользователя
			 * @example Фамилия
			 */
			last_name: string;
			/**
			 * @description id пользователя в телеграм
			 * @example 12342332
			 */
			tg_id: number;
		};
		BlockedUserDto: {
			/**
			 * @description id сообщения
			 * @example 1
			 */
			userId: number;
			/**
			 * @description Индекс действия по отношению к сообщениям
			 * @example 1
			 */
			selectedPunishmentIndex: number;
		};
		Date: Record<string, never>;
		CreatePublicationDto: {
			id_user: number;
			secret: string;
			form: components['schemas']['FormDto'];
		};
		CreateGroupDto: {
			/**
			 * @description Название группы
			 * @example Поиск ООП
			 */
			groupName: string;
			/**
			 * @description Задача группы
			 * @example Совместными усилиями определить ООП
			 */
			groupTask: string;
			/**
			 * @description Локация группы
			 * @example Район
			 */
			location: string;
		};
		CreatePostToChatDto: {
			/**
			 * @description ID чата
			 * @example 5
			 */
			groupId: number;
			location: string;
			form: components['schemas']['FormDto'];
		};
		LogoutUserDto: {
			/**
			 * @description ID user
			 * @example 1
			 */
			id: number;
			/**
			 * @description uuid for refreshToken
			 * @example sdfasdfvcvd
			 */
			uuid: string;
			/**
			 * @description Exit for all devices
			 * @example true
			 */
			allDeviceExit: boolean;
		};
		CreateRegistrationDto: {
			/**
			 * @description id пользователя
			 * @example 1
			 */
			id: number;
			/**
			 * @description Проверка состояния
			 * @example sdfsfsdgggg
			 */
			secret: string;
			/**
			 * @description uuid для используемого устройства
			 * @example sdfsfsdgggg
			 */
			uuid: string;
		};
		VkLoginSdkDto: {
			/**
			 * @description uuid VK
			 * @example QGvH-8oEHe7seNqn5
			 */
			uuid: string;
			/**
			 * @description Токен доступа VK
			 * @example Q-w-rLTxyi02R206ST3-lJi7siJazRnjIw3lU6ISIotanzuIibpSqzwONRZb-gSyC1OeFUd2uBzGX2QWPxMoPcPtA8EqnPp77NjnxZ2Vthx50nSeJ1D-plvRXMkv0JJofSMYknato7__m4UXYnak9QmMbnmRym0chJpW0im3uyyvzDehy2vNYNgMv4ZdB_lvrpxRh6HDyZugVFVTBH-B68XuHg-xGAB0OtRTjWd4yP_atlryHaeZHH5kcyPZQWsi2jhS2iawbRXqccrmJF0DurCcLG2Yw4UbzHfdV0DBOlhhtd86os81ZgMrSzTtLx1utIvWu9-EdvGIqZBOXteZS-uRLQzZKL86_08IBKfC0gaDSAWtgQjphXfC7EJCRLZdZB7T3LLc2Ce4jeq3Y4JzNuAEMA
			 */
			token: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	AdminController_reportViolation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['FoulSendMessageDto'];
			};
		};
		responses: {
			/** @description Сообщение о нарушении правил доставлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': string;
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AdminController_getFoulMessages: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Сообщение о нарушении правил доставлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': string;
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AdminController_fetchCleaningIsComplete: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': number;
			};
		};
		responses: {
			/** @description Сообщение о нарушении правил доставлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': string;
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	FilesController_uploadFile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Файл загружен */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	FilesController_getFile: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				filename: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_addMessage: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateMessageDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_getAllMessage: {
		parameters: {
			query: {
				/** @description ID учредителя */
				id: string;
				/** @description ID первого сообщения */
				pageNumber: string;
				/** @description Секретное слово */
				secret: string;
				/** @description Радиус проживания */
				location: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_getCountNoReadMessages: {
		parameters: {
			query: {
				/** @description id пользователя */
				id: string;
				/** @description Проверка состояния */
				secret: string;
				/** @description Название планеты */
				world: string;
				/** @description Название страны */
				country: string;
				/** @description Название региона */
				region: string;
				/** @description Название района */
				locality: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EndMessageDto'];
			};
		};
		responses: {
			/** @description Декларация добавлена */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_getEndReadMessagesId: {
		parameters: {
			query: {
				/** @description id пользователя */
				id: string;
				/** @description Проверка состояния */
				secret: string;
				/** @description Название планеты */
				world: string;
				/** @description Название страны */
				country: string;
				/** @description Название региона */
				region: string;
				/** @description Название района */
				locality: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EndMessageDto'];
			};
		};
		responses: {
			/** @description Данные получены */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_setEndReadMessagesId: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EndReadMessageDto'];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_getMessageFromId: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': number;
			};
		};
		responses: {
			/** @description Данные получены */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	MessagesController_blockedMessages: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockedMessagesDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	ResidencyController_getAllResydencys: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Получены данные пользователей */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Residency'][];
				};
			};
			/** @description Пользователь не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	RolesController_getAllRoles: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	RolesController_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateRoleDto'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	TokensController_refreshTokens: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UuidDevice'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OutputUserAndTokens'];
				};
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_getAllUsers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Получены данные пользователей */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Пользователь не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_userAddRole: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddRoleDto'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен или роль пользователя */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_userRemoveRole: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddRoleDto'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен или роль пользователя */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_createResidency: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateResidencyDto'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_addDeclaration: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateDeclarationDto'];
			};
		};
		responses: {
			/** @description Декларация добавлена */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_getDeclaration: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор пользователя в базе данных */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Декларация добавлена */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_udatePersonaleData: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Кодовое слово */
				secret: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdatePersonaleDto'];
			};
		};
		responses: {
			/** @description Декларация добавлена */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_uploadAvatar: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Аватар изменен */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_blockedUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockedUserDto'];
			};
		};
		responses: {
			/** @description Пользователь заблокирован */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_checkBlocked: {
		parameters: {
			query: {
				userId: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Сообщение о нарушении правил доставлено */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Date'];
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UsersController_getUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Получение пользователя по его Id */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Date'];
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	LocationController_crateLocation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateLocationDto'];
			};
		};
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен или роль пользователя */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	LocationController_getAllCountry: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	LocationController_getRegions: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				country: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	LocationController_getLocality: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				region: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Операция прошла успешно. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	PublicationsController_addPublication: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreatePublicationDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	PublicationsController_getAllPublication: {
		parameters: {
			query: {
				/** @description Название страны */
				country: string;
				/** @description Название региона */
				region: string;
				/** @description Название района */
				locality: string;
				/** @description Номер страницы */
				pageNumber: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Список публикаций */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Publications'][];
				};
			};
			/** @description Некорректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	PublicationsController_getDeclaration: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор публикации в базе данных */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Публикация получена */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	PublicationsController_getUserPublication: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateMessageDto'];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	PublicationsController_blockedPublications: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockedMessagesDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_createGroup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateGroupDto'];
			};
		};
		responses: {
			/** @description Группа создана */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_getAllPublication: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_getGroupFromId: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Идентификатор группы в базе данных */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Группа получена */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_getAllChatPosts: {
		parameters: {
			query: {
				/** @description ID группы */
				groupId: string;
				/** @description Номер страницы */
				pageNumber: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_addMessage: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreatePostToChatDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_joinTheGroup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Учредитель вступил в группу */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_leaveTheGroup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Учредитель вышел из группы */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_getPostGroupFromId: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': number;
			};
		};
		responses: {
			/** @description Данные получены */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GroupsController_blockedPostGroup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockedMessagesDto'];
			};
		};
		responses: {
			/** @description Сообщение добавлено */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LogoutUserDto'];
			};
		};
		responses: {
			/** @description Пользователь успешно разлогинен */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Пользователь не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_setRegistration: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateRegistrationDto'];
			};
		};
		responses: {
			/** @description Успешная регистрация */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OutputUserAndTokens'];
				};
			};
			/** @description Неккоректные данные */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_deleteProfile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LogoutUserDto'];
			};
		};
		responses: {
			/** @description Пользователь успешно разлогинен */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Некоректный JWT токен */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Пользователь не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_restoreProfile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LogoutUserDto'];
			};
		};
		responses: {
			/** @description Пользователь успешно восстановлен */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Пользователь не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_registrationVk: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VkLoginSdkDto'];
			};
		};
		responses: {
			/** @description Успешная регистрация */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['User'];
				};
			};
			/** @description Пользователь уже существует */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AuthController_checkAdmin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description У пользователя есть права администратора. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description JWT токен не указан в заголовках */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description У пользователя нет прав администратора. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	TelegramController_handleUpdate: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
