name: Build and Deploy to Server

on:
  push:
    branches:
      - main

env:
  DOCKER_COMPOSE_FILE: docker-compose.yml
  SERVER_USER: sumnic            # ← замени на имя пользователя сервера (например ubuntu)
  SERVER_HOST: 77.222.55.226      # ← замени на IP или домен
  DEPLOY_PATH: /home/sumnic/rodnaya-app  # ← путь до проекта на сервере

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./server/.env.prod
          echo "MODE=prod" >> .env
          echo "VITE_VK_ID_APP_PROD=${{ secrets.VITE_VK_ID_APP_PROD }}" >> ./client/.env
          echo "VITE_YANDEX_COUNTER_ID_PROD=104841811" >> ./client/.env
          MODE=prod docker compose -f docker-compose.yml -f docker-compose.prod.yml build --build-arg IMAGE_TAG=${IMAGE_TAG}
          MODE=prod docker compose -f docker-compose.yml -f docker-compose.prod.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # передаём переменные окружения на сервер
          envs: DEPLOY_PATH

          script: |
            cd "$DEPLOY_PATH"
            git pull
            MODE=prod docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            MODE=prod docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
